services:
  fhir:
    image: hapiproject/hapi:latest
    restart: unless-stopped
    ports:
      - "8888:8080"
    networks:
      - local

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - local

  django-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - local
    depends_on:
      - fhir
      - redis

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - "./.infra/prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - local
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'

networks:
  local:
    driver: bridge